version: 0.1
phases: 
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=awsrepo -Dsonar.organisation=asologon10 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=95893b0c994d44963535c2b7762411674e75284c
